name: keeparr-backend
services:
  # app:
  #   image: imbios/bun-node
  #   command: sh -c "bun install && bun run start:debug"
  #   ports:
  #     - '3001:3001'
  #   working_dir: /app
  #   volumes:
  #     - type: bind
  #       source: ./
  #       target: /app
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   network_mode: bridge
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      # Bind explicitly to 127.0.0.1
      - '127.0.0.1:9000:9000'
      - '9001:9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_storage:
